# Test fixture harness for cluster.tftest.hcl.
#
# Two jobs:
#
#   1. Stage kms-output/root-ca.pem so main.tf's
#      `locals.oidc_ca_pem = file(...)` resolves at plan time. Uses a
#      null_resource + local-exec (create-only) so the file persists
#      across `tofu test`'s automatic destroy.
#
#   2. Declare the same set of root-module input variables as main.tf,
#      so cluster.tftest.hcl can assert on their values from a run block
#      that targets THIS module (avoiding the OpenTofu 1.11 limitation
#      around mock_provider + computed list-blocks on scaleway_vpc_private_network
#      — see cluster.tftest.hcl for the details).
#
# Purely local. No cloud APIs are touched.

terraform {
  required_version = ">= 1.6"
  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }
}

variable "controlplane_count" {
  type    = number
  default = 3
}

variable "worker_count" {
  type    = number
  default = 3
}

variable "cp_instance_type" {
  type    = string
  default = "DEV1-M"
}

variable "worker_instance_type" {
  type    = string
  default = "DEV1-L"
}

variable "ephemeral_disk_size" {
  type    = number
  default = 25
}

variable "enable_dns" {
  type    = bool
  default = false
}

variable "dns_subdomain" {
  type    = string
  default = "api.talos"
}

variable "talos_version" {
  type    = string
  default = "v1.12.4"
}

variable "kubernetes_version" {
  type    = string
  default = "1.35.0"
}

locals {
  # When this module is invoked as a `run { module { source = "./tests/setup" } }`
  # from envs/scaleway's cluster.tftest.hcl, path.root resolves to ./tests/setup
  # (the setup module itself). The real root module under test (envs/scaleway)
  # reads kms-output/root-ca.pem via `${path.module}/../../kms-output/...` which
  # from envs/scaleway is repo-root/kms-output. So we walk 4 levels up:
  # setup → tests → scaleway → envs → repo-root.
  fixture_dir  = "${path.root}/../../../../kms-output"
  fixture_file = "${local.fixture_dir}/root-ca.pem"
}

resource "null_resource" "root_ca_fixture" {
  triggers = {
    path = local.fixture_file
  }

  provisioner "local-exec" {
    interpreter = ["/bin/sh", "-c"]
    command     = <<-EOT
      mkdir -p "${local.fixture_dir}"
      cat > "${local.fixture_file}" <<'PEM'
      -----BEGIN CERTIFICATE-----
      FAKE CA PEM - tofu test fixture only. Never used by a running cluster.
      The real CA is generated by 'make bootstrap' (bootstrap/tofu).
      -----END CERTIFICATE-----
      PEM
    EOT
  }
}

output "fixture_path" {
  value = local.fixture_file
}
