apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: containeroo
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.containeroo.ch
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vmware-tanzu
  namespace: flux-system
spec:
  interval: 1h
  url: https://vmware-tanzu.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.goharbor.io
