#!/bin/bash
# Platform pod launcher — runs on the CI VM.
#
# Artifacts are generated by OpenTofu. The shared preflight validates the
# actual ConfigMap seal key and migrates legacy setup state BEFORE deletion.

set -euo pipefail
umask 077

WORKDIR=${BOOTSTRAP_WORKDIR:-/opt/woodpecker}

# Permissions are tightened before reading or combining any uploaded secret.
test -d "$WORKDIR" && test ! -L "$WORKDIR"
chmod 0700 "$WORKDIR"
for file in configmap.yaml secrets.yaml unseal.key.bin platform-pod.yaml; do
  test -f "$WORKDIR/$file" && test ! -L "$WORKDIR/$file"
  chmod 0600 "$WORKDIR/$file"
done
if [ -e "$WORKDIR/pod-with-secrets.yaml" ] || [ -L "$WORKDIR/pod-with-secrets.yaml" ]; then
  test -f "$WORKDIR/pod-with-secrets.yaml" && test ! -L "$WORKDIR/pod-with-secrets.yaml"
  chmod 0600 "$WORKDIR/pod-with-secrets.yaml"
fi

# Atomic private output also fixes permissions on manifests from older runs.
combined=$(mktemp "$WORKDIR/.pod-with-secrets.XXXXXX")
trap 'rm -f "$combined"' EXIT
{ cat "$WORKDIR/configmap.yaml"; printf '\n---\n';
  cat "$WORKDIR/secrets.yaml"; printf '\n---\n';
  cat "$WORKDIR/platform-pod.yaml"; } > "$combined"
python3 "$WORKDIR/bootstrap-preflight.py" --replace \
  --manifest "$combined" --uploaded-key "$WORKDIR/unseal.key.bin"
mv -f "$combined" "$WORKDIR/pod-with-secrets.yaml"
rm -f "$WORKDIR/unseal.key.bin"

# ─── Gitea admin user (idempotent) ─────────────────────────────────────
#
# Wait for the HTTP listener, then create the admin via the in-pod CLI.
# Bypasses the cookie-based signup form which is brittle from inside the
# sidecar. `gitea admin user create` returns non-zero if the user already
# exists; tolerate only that specific condition.

echo "Waiting for Gitea HTTP..."
gitea_ready=0
for _ in $(seq 1 60); do
  if curl -sf -o /dev/null "http://localhost:3000/api/v1/version" 2>/dev/null; then
    gitea_ready=1
    break
  fi
  sleep 2
done
if [ "$gitea_ready" -ne 1 ]; then
  echo "FATAL: Gitea HTTP did not become ready after 120s." >&2
  exit 1
fi

echo "Creating Gitea admin user '${GITEA_ADMIN}' (idempotent)..."
gitea_output="$(podman exec -u git platform-gitea gitea admin user create \
  --username "${GITEA_ADMIN}" --password "${GITEA_PASSWORD}" --email "admin@ci.local" \
  --admin --must-change-password=false 2>&1)" || {
  if printf '%s\n' "$gitea_output" | grep -qi 'already exists\|user.*exists'; then
    echo "[setup] Gitea admin user already exists — OK"
  else
    printf '%s\n' "$gitea_output" >&2
    echo "FATAL: failed to create Gitea admin user." >&2
    exit 1
  fi
}

# ─── Wait for setup sidecar to finish ──────────────────────────────────

echo "Waiting for platform setup..."
setup_ready=0
for _ in $(seq 1 120); do
  if podman logs platform-tofu-setup 2>&1 | grep -q '\[setup\] ==='; then
    setup_ready=1
    break
  fi
  sleep 5
done
if [ "$setup_ready" -ne 1 ]; then
  echo "FATAL: platform setup sidecar did not finish after 600s." >&2
  podman logs platform-tofu-setup >&2 || true
  exit 1
fi

# ─── Export tokens from the setup sidecar ──────────────────────────────

install -d -m 0700 /opt/talos/kms-output
podman cp platform-tofu-setup:/kms-output/. /opt/talos/kms-output/
find /opt/talos/kms-output -type f -exec chmod 0600 {} +

echo "========================================="
echo "  Bootstrap ready; CI activation is a separate operator step"
echo "  See docs/how-to/woodpecker-activate.md"
echo "========================================="
