#!/bin/bash
# Platform pod launcher — runs on the CI VM.
#
# This script is intentionally tiny. It does NO file generation, NO secret
# rolling, NO key derivation. Every state-bearing artifact (configmap,
# secrets, unseal.key, pod yaml) is uploaded by Terraform from
# `envs/scaleway/ci/files/` (generated by local_file/local_sensitive_file
# resources). All this script does is:
#   1. Install the seal key (idempotent — never overwrite)
#   2. Re-launch the platform pod via `podman play kube`
#   3. Create the Gitea admin user if missing
#   4. Wait for the platform setup sidecar to finish
#   5. Copy the issued KMS tokens out of the sidecar
#
# Postmortem 2026-04-26: the previous setup.sh.tpl generated state-bearing
# content on the VM (openssl rand for the seal key), so any re-run nuked
# the existing OpenBao raft data. This launcher cannot recreate that bug
# because it never runs `openssl rand` or any equivalent.

set -euo pipefail

WORKDIR=/opt/woodpecker

# ─── Seal key install (idempotent) ─────────────────────────────────────
#
# The TF-generated key arrives as $WORKDIR/unseal.key.bin. We move it to
# $WORKDIR/unseal.key only on first install. If unseal.key already exists
# AND non-empty, we keep it (bao raft data depends on this exact value).
# A divergence between TF-supplied and on-disk values means tfstate was
# wiped and regenerated — we WARN but the on-disk value wins.

test -s "$WORKDIR/unseal.key.bin" || {
  echo "FATAL: $WORKDIR/unseal.key.bin missing — TF should have uploaded it." >&2
  exit 1
}

if [ -s "$WORKDIR/unseal.key" ]; then
  if ! cmp -s "$WORKDIR/unseal.key" "$WORKDIR/unseal.key.bin"; then
    echo "[seal] WARN: on-disk key != TF-supplied key. tfstate likely lost+regenerated."
    echo "[seal] On-disk wins — bao raft data depends on it. To recover tfstate, run:"
    echo "[seal]   scp root@<ci-ip>:$WORKDIR/unseal.key kms-output/unseal.key.recovered"
  else
    echo "[seal] on-disk key matches TF state (good)."
  fi
else
  echo "[seal] first install: copying TF-supplied key to $WORKDIR/unseal.key"
  cp "$WORKDIR/unseal.key.bin" "$WORKDIR/unseal.key"
  chmod 0400 "$WORKDIR/unseal.key"
fi

# Hard sanity: a 32-byte key. Refuse to recreate the platform pod with a
# malformed key file, since that would risk the bao data again.
test "$(stat -c %s "$WORKDIR/unseal.key" 2>/dev/null)" = "32" || {
  echo "FATAL: $WORKDIR/unseal.key is not 32 bytes. Refusing to launch." >&2
  exit 1
}

# Wipe the .tf copy after install — there's no reason to keep two copies.
rm -f "$WORKDIR/unseal.key.bin"

# ─── Launch the platform pod ───────────────────────────────────────────
#
# Multi-doc: pod manifest first, secrets appended. `podman play kube`
# reads multi-doc YAML; --configmap loads the configmap doc separately
# (needed because podman play kube refuses Secret in --configmap).
# An explicit `---` separator is required between the two docs since
# platform-pod.yaml may not end with one.

{ cat "$WORKDIR/platform-pod.yaml"; echo '---'; cat "$WORKDIR/secrets.yaml"; } \
  > "$WORKDIR/pod-with-secrets.yaml"

# Idempotent: clean up any partial state from a previous failed run.
podman pod rm -f platform 2>/dev/null || true
podman secret rm platform-secrets 2>/dev/null || true

podman play kube "$WORKDIR/pod-with-secrets.yaml" \
  --configmap="$WORKDIR/configmap.yaml"

# ─── Gitea admin user (idempotent) ─────────────────────────────────────
#
# Wait for the HTTP listener, then create the admin via the in-pod CLI.
# Bypasses the cookie-based signup form which is brittle from inside the
# sidecar. `gitea admin user create` returns non-zero if the user already
# exists; we treat that as success.

echo "Waiting for Gitea HTTP..."
for _ in $(seq 1 60); do
  curl -sf -o /dev/null "http://localhost:3000/api/v1/version" 2>/dev/null && break
  sleep 2
done

echo "Creating Gitea admin user '${GITEA_ADMIN}' (idempotent)..."
podman exec -u git platform-gitea gitea admin user create \
  --username "${GITEA_ADMIN}" --password "${GITEA_PASSWORD}" --email "admin@ci.local" \
  --admin --must-change-password=false 2>&1 \
  || echo "[setup] gitea admin user create returned non-zero (user may already exist — OK)"

# ─── Wait for setup sidecar to finish ──────────────────────────────────

echo "Waiting for platform setup..."
for _ in $(seq 1 120); do
  podman logs platform-tofu-setup 2>&1 | grep -q '\[setup\] ===' && break
  sleep 5
done

# ─── Export tokens from the setup sidecar ──────────────────────────────

mkdir -p /opt/talos/kms-output
podman cp platform-tofu-setup:/kms-output/. /opt/talos/kms-output/

echo "========================================="
echo "  Platform ready"
echo "========================================="
