apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karpenter-scaleway-credentials
  namespace: autoscaling
spec:
  refreshInterval: 5m
  secretStoreRef: {kind: ClusterSecretStore, name: openbao-infra}
  target:
    name: karpenter-scaleway-credentials
  data:
    - secretKey: SCW_ACCESS_KEY
      remoteRef: {key: autoscaling/scaleway, property: access_key}
    - secretKey: SCW_SECRET_KEY
      remoteRef: {key: autoscaling/scaleway, property: secret_key}
    - secretKey: SCW_DEFAULT_PROJECT_ID
      remoteRef: {key: autoscaling/scaleway, property: project_id}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karpenter-talos-worker
  namespace: autoscaling
spec:
  refreshInterval: 5m
  secretStoreRef: {kind: ClusterSecretStore, name: openbao-infra}
  target:
    name: karpenter-talos-worker
  data:
    - secretKey: machineconfig
      remoteRef: {key: autoscaling/talos-worker, property: machineconfig}
