apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garage-secrets
  namespace: garage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-infra
    kind: ClusterSecretStore
  target:
    name: garage-secrets
    template:
      engineVersion: v2
      data:
        values.yaml: |
          garage:
            rpcSecret: {{ .rpc_secret }}
            admin:
              token: {{ .admin_token }}
  data:
    - secretKey: rpc_secret
      remoteRef:
        key: secret/data/storage/garage
        property: rpc_secret
    - secretKey: admin_token
      remoteRef:
        key: secret/data/storage/garage
        property: admin_token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-secrets
  namespace: storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-infra
    kind: ClusterSecretStore
  target:
    name: harbor-secrets
    template:
      engineVersion: v2
      data:
        values.yaml: |
          harborAdminPassword: {{ .admin_password }}
  data:
    - secretKey: admin_password
      remoteRef:
        key: secret/data/storage/harbor
        property: admin_password
