apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../stacks/external-secrets/flux
  - ../../stacks/cni/flux
  - ../../stacks/monitoring/flux
  - ../../stacks/pki/flux
  - ../../stacks/identity/flux
  - ../../stacks/security/flux
  - ../../stacks/storage/flux
