apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease-prometheus-adapter.yaml
  - helmrelease-vpa.yaml
  - helmrelease-keda.yaml
configMapGenerator:
  - name: prometheus-adapter-values
    namespace: autoscaling
    files: [values.yaml=values-prometheus-adapter.yaml]
  - name: vpa-values
    namespace: autoscaling
    files: [values.yaml=values-vpa.yaml]
  - name: keda-values
    namespace: autoscaling
    files: [values.yaml=values-keda.yaml]
generatorOptions:
  disableNameSuffixHash: true
