apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease-vm-stack.yaml
  - helmrelease-vlogs-single.yaml
  - helmrelease-vlogs-collector.yaml
  - helmrelease-headlamp.yaml
  - configmap-dashboard.yaml
