apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hydra-secrets
  namespace: identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-infra
    kind: ClusterSecretStore
  target:
    name: hydra-secrets
    template:
      engineVersion: v2
      data:
        values.yaml: |
          hydra:
            config:
              secrets:
                system:
                  - {{ .system_secret }}
  data:
    - secretKey: system_secret
      remoteRef:
        key: identity/hydra
        property: system_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pomerium-secrets
  namespace: identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-infra
    kind: ClusterSecretStore
  target:
    name: pomerium-secrets
    template:
      engineVersion: v2
      data:
        values.yaml: |
          config:
            sharedSecret: {{ .shared_secret }}
            cookieSecret: {{ .cookie_secret }}
          authenticate:
            idp:
              clientSecret: {{ .client_secret }}
  data:
    - secretKey: shared_secret
      remoteRef:
        key: identity/pomerium
        property: shared_secret
    - secretKey: cookie_secret
      remoteRef:
        key: identity/pomerium
        property: cookie_secret
    - secretKey: client_secret
      remoteRef:
        key: identity/pomerium
        property: client_secret
