//go:build !ignore_autogenerated

// Code generated by controller-gen (hand-maintained for the M0 spike). DO NOT EDIT.

package v1alpha1

import (
	"github.com/awslabs/operatorpkg/status"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayEMNodeClass) DeepCopyInto(out *ScalewayEMNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayEMNodeClass.
func (in *ScalewayEMNodeClass) DeepCopy() *ScalewayEMNodeClass {
	if in == nil {
		return nil
	}
	out := new(ScalewayEMNodeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalewayEMNodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayEMNodeClassList) DeepCopyInto(out *ScalewayEMNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalewayEMNodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayEMNodeClassList.
func (in *ScalewayEMNodeClassList) DeepCopy() *ScalewayEMNodeClassList {
	if in == nil {
		return nil
	}
	out := new(ScalewayEMNodeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalewayEMNodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayEMNodeClassSpec) DeepCopyInto(out *ScalewayEMNodeClassSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayEMNodeClassSpec.
func (in *ScalewayEMNodeClassSpec) DeepCopy() *ScalewayEMNodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(ScalewayEMNodeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayEMNodeClassStatus) DeepCopyInto(out *ScalewayEMNodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]status.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayEMNodeClassStatus.
func (in *ScalewayEMNodeClassStatus) DeepCopy() *ScalewayEMNodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(ScalewayEMNodeClassStatus)
	in.DeepCopyInto(out)
	return out
}
