# Pomerium — Zero-trust access proxy
# Minimal config for POC

authenticate:
  idp:
    provider: oidc
    providerUrl: https://hydra-public.identity.svc:4444/
    clientID: pomerium
    clientSecret: ${client_secret}

proxy:
  replicaCount: 1

authorize:
  replicaCount: 1

config:
  sharedSecret: "${shared_secret}"
  cookieSecret: "${cookie_secret}"

ingress:
  enabled: false
