apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  releaseName: garage
  storageNamespace: garage
  interval: 30m
  chart:
    spec:
      chart: ./stacks/storage/chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: management
        namespace: flux-system
  # Garage becomes Ready only after the following layout Job.
  install:
    disableWait: true
  upgrade:
    disableWait: true
  valuesFrom:
    - kind: ConfigMap
      name: garage-values
    - kind: Secret
      name: garage-secrets
