apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao-infra
spec:
  provider:
    vault:
      server: "http://openbao-infra.secrets.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: openbao-infra-token
          namespace: external-secrets
          key: token
