terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }
    vault = {
      source  = "hashicorp/vault"
      version = "~> 4.0"
    }
  }
}

# ═══════════════════════════════════════════════════════════════════════
# Secrets from bootstrap OpenBao (generated by sidecar, read-only)
# ═══════════════════════════════════════════════════════════════════════

provider "vault" {
  address         = var.vault_address
  token           = var.vault_token
  skip_tls_verify = true
}

data "vault_kv_secret_v2" "storage" {
  mount = "secret"
  name  = "cluster/storage"
}

locals {
  secrets = data.vault_kv_secret_v2.storage.data
}

provider "kubernetes" {
  config_path = var.kubeconfig_path
}

provider "helm" {
  kubernetes {
    config_path = var.kubeconfig_path
  }
}

# ─── Storage Namespace ───────────────────────────────────────────────

resource "kubernetes_namespace" "storage" {
  metadata {
    name = "storage"
    labels = {
      "pod-security.kubernetes.io/enforce" = "privileged"
    }
  }
}

# ─── local-path-provisioner (default StorageClass) ───────────────────

resource "helm_release" "local_path_provisioner" {
  name             = "local-path-provisioner"
  repository       = "https://charts.containeroo.ch"
  chart            = "local-path-provisioner"
  version          = var.local_path_provisioner_version
  namespace        = "storage"
  create_namespace = false

  values = [file("${path.module}/values-local-path.yaml")]

  depends_on = [kubernetes_namespace.storage]
}

# ─── Garage (S3-compatible object store) ──────────────────────────────

resource "helm_release" "garage" {
  name             = "garage"
  chart            = "${path.module}/chart"
  namespace        = "garage"
  create_namespace = true
  wait             = false # Garage returns 503 until layout is configured

  values = [templatefile("${path.module}/values-garage.yaml", {
    garage_rpc_secret  = local.secrets["garage_rpc_secret"]
    garage_admin_token = local.secrets["garage_admin_token"]
  })]

  depends_on = [helm_release.local_path_provisioner]
}

# ─── Garage setup Job (layout, buckets, API keys, K8s secrets) ───────
# Runs in-cluster as a K8s Job. Creates:
#   - velero-s3-credentials (storage ns, INI format)
#   - harbor-s3-credentials (storage ns, plain key/secret)

resource "kubernetes_service_account_v1" "garage_setup" {
  metadata {
    name      = "garage-setup"
    namespace = "garage"
  }
  depends_on = [helm_release.garage]
}

resource "kubernetes_role_v1" "garage_setup_storage" {
  metadata {
    name      = "garage-setup"
    namespace = "storage"
  }
  rule {
    api_groups = [""]
    resources  = ["secrets"]
    verbs      = ["get", "create", "update", "patch"]
  }
}

resource "kubernetes_role_binding_v1" "garage_setup_storage" {
  metadata {
    name      = "garage-setup"
    namespace = "storage"
  }
  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "Role"
    name      = kubernetes_role_v1.garage_setup_storage.metadata[0].name
  }
  subject {
    kind      = "ServiceAccount"
    name      = kubernetes_service_account_v1.garage_setup.metadata[0].name
    namespace = "garage"
  }
}

resource "kubernetes_job_v1" "garage_setup" {
  metadata {
    name      = "garage-setup-${substr(md5(local.secrets["garage_admin_token"]), 0, 8)}"
    namespace = "garage"
  }

  spec {
    backoff_limit = 5
    completions   = 1

    template {
      metadata {
        labels = { app = "garage-setup" }
      }
      spec {
        service_account_name = kubernetes_service_account_v1.garage_setup.metadata[0].name
        restart_policy       = "OnFailure"

        container {
          name  = "setup"
          image = "alpine:3.21"

          env {
            name  = "GARAGE_ADMIN_TOKEN"
            value = local.secrets["garage_admin_token"]
          }
          env {
            name  = "GARAGE_API"
            value = "http://garage-0.garage-headless.garage.svc.cluster.local:3903/v2"
          }
          env {
            name  = "KUBE_API"
            value = "https://kubernetes.default.svc"
          }

          command = ["/bin/sh", "-c"]
          args = [<<-SCRIPT
            set -eu
            apk add --no-cache curl jq >/dev/null 2>&1

            TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            CA=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            garage() { curl -sf -H "Authorization: Bearer $GARAGE_ADMIN_TOKEN" -H "Content-Type: application/json" "$@"; }
            kube()   { curl -sf --cacert $CA -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" "$@"; }

            # ─── Wait for Garage admin API ──────────────────────────────
            echo "Waiting for Garage admin API..."
            for i in $(seq 1 60); do
              garage "$GARAGE_API/GetClusterStatus" >/dev/null 2>&1 && break
              echo "  attempt $i/60..." && sleep 5
            done
            garage "$GARAGE_API/GetClusterStatus" >/dev/null || { echo "ERROR: Garage admin API unreachable"; exit 1; }
            echo "Garage API ready."

            # ─── Layout ─────────────────────────────────────────────────
            LAYOUT=$(garage "$GARAGE_API/GetClusterLayout")
            LAYOUT_VER=$(echo "$LAYOUT" | jq -r '.version')
            if [ "$LAYOUT_VER" = "0" ]; then
              echo "Configuring layout..."
              NODES=$(garage "$GARAGE_API/GetClusterStatus" | jq '[.nodes[] | select(.isUp) | {id: .id, zone: "dc1", capacity: 5000000000, tags: []}]')
              garage -X POST -d "$NODES" "$GARAGE_API/UpdateClusterLayout" >/dev/null
              garage -X POST -d "{\"version\": 1}" "$GARAGE_API/ApplyClusterLayout" >/dev/null
              echo "Layout applied (version 1)."
            else
              echo "Layout already configured (version $LAYOUT_VER)."
            fi

            # ─── Buckets ────────────────────────────────────────────────
            for BUCKET in velero-backups harbor-registry; do
              if garage "$GARAGE_API/GetBucketInfo?globalAlias=$BUCKET" >/dev/null 2>&1; then
                echo "Bucket '$BUCKET' exists."
              else
                echo "Creating bucket '$BUCKET'..."
                garage -X POST -d "{\"globalAlias\": \"$BUCKET\"}" "$GARAGE_API/CreateBucket" >/dev/null
              fi
            done

            # ─── Helper: create key + grant + K8s secret ────────────────
            create_key() {
              KEY_NAME=$1; BUCKET=$2; SECRET_NS=$3; SECRET_NAME=$4; SECRET_FORMAT=$5

              # Check if K8s secret already exists
              if kube "$KUBE_API/api/v1/namespaces/$SECRET_NS/secrets/$SECRET_NAME" >/dev/null 2>&1; then
                echo "Secret '$SECRET_NAME' already exists, skipping key '$KEY_NAME'."
                return 0
              fi

              # Create key
              echo "Creating key '$KEY_NAME'..."
              KEY_JSON=$(garage -X POST -d "{\"name\": \"$KEY_NAME\"}" "$GARAGE_API/CreateKey")
              ACCESS=$(echo "$KEY_JSON" | jq -r '.accessKeyId')
              SECRET=$(echo "$KEY_JSON" | jq -r '.secretAccessKey')
              [ -z "$ACCESS" ] || [ "$ACCESS" = "null" ] && { echo "ERROR: key creation failed"; exit 1; }

              # Grant permissions
              BUCKET_ID=$(garage "$GARAGE_API/GetBucketInfo?globalAlias=$BUCKET" | jq -r '.id')
              garage -X POST -d "{\"bucketId\": \"$BUCKET_ID\", \"accessKeyId\": \"$ACCESS\", \"permissions\": {\"read\": true, \"write\": true, \"owner\": true}}" \
                "$GARAGE_API/AllowBucketKey" >/dev/null

              # Create K8s secret
              if [ "$SECRET_FORMAT" = "ini" ]; then
                CLOUD=$(printf '[default]\naws_access_key_id=%s\naws_secret_access_key=%s\n' "$ACCESS" "$SECRET" | base64 | tr -d '\n')
                BODY="{\"apiVersion\":\"v1\",\"kind\":\"Secret\",\"metadata\":{\"name\":\"$SECRET_NAME\",\"namespace\":\"$SECRET_NS\"},\"data\":{\"cloud\":\"$CLOUD\"}}"
              else
                AK=$(printf '%s' "$ACCESS" | base64 | tr -d '\n')
                SK=$(printf '%s' "$SECRET" | base64 | tr -d '\n')
                BODY="{\"apiVersion\":\"v1\",\"kind\":\"Secret\",\"metadata\":{\"name\":\"$SECRET_NAME\",\"namespace\":\"$SECRET_NS\"},\"data\":{\"access_key\":\"$AK\",\"secret_key\":\"$SK\"}}"
              fi
              kube -X POST -d "$BODY" "$KUBE_API/api/v1/namespaces/$SECRET_NS/secrets" >/dev/null
              echo "  Key '$KEY_NAME' created ($ACCESS), secret '$SECRET_NAME' written."
            }

            create_key "velero-key"  "velero-backups"   "storage" "velero-s3-credentials"  "ini"
            create_key "harbor-key"  "harbor-registry"  "storage" "harbor-s3-credentials"  "plain"

            echo "Garage setup complete."
          SCRIPT
          ]
        }
      }
    }
  }

  wait_for_completion = true

  timeouts {
    create = "10m"
  }

  depends_on = [
    helm_release.garage,
    kubernetes_namespace.storage,
    kubernetes_role_binding_v1.garage_setup_storage,
  ]
}

# ─── Velero (backup & DR → Garage S3) ────────────────────────────────

resource "helm_release" "velero" {
  name             = "velero"
  repository       = "https://vmware-tanzu.github.io/helm-charts"
  chart            = "velero"
  version          = var.velero_version
  namespace        = "storage"
  create_namespace = false
  timeout          = 600

  values = [templatefile("${path.module}/values-velero.yaml", {
    velero_bucket = var.velero_bucket
    s3_url        = var.s3_url
  })]

  depends_on = [kubernetes_namespace.storage, kubernetes_job_v1.garage_setup]
}

# ─── Harbor (container registry with Garage S3 backend) ──────────────

data "kubernetes_secret" "harbor_s3" {
  depends_on = [kubernetes_job_v1.garage_setup]

  metadata {
    name      = "harbor-s3-credentials"
    namespace = "storage"
  }
}

resource "helm_release" "harbor" {
  name             = "harbor"
  repository       = "https://helm.goharbor.io"
  chart            = "harbor"
  version          = var.harbor_version
  namespace        = "storage"
  create_namespace = false
  timeout          = 600

  values = [
    file("${path.module}/values-harbor.yaml"),
    sensitive(yamlencode({
      harborAdminPassword = local.secrets["harbor_admin_password"]
      persistence = {
        imageChartStorage = {
          s3 = {
            accesskey = data.kubernetes_secret.harbor_s3.data["access_key"]
            secretkey = data.kubernetes_secret.harbor_s3.data["secret_key"]
          }
        }
      }
    })),
  ]

  depends_on = [kubernetes_namespace.storage, kubernetes_job_v1.garage_setup]
}
